In [ ]:
import pandas as pd
import numpy as np
from tabulate import tabulate
import re
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df1 = pd.read_csv('/content/df1.csv')

df1 = df1.dropna()

columns_to_clean = ['Postal Code', 'Model Year', 'Electric Range', 'Base MSRP', 'Legislative District', 'DOL Vehicle ID']

for col in columns_to_clean:
    df1[col] = df1[col].apply(lambda x: re.sub(r'[^0-9]+', '', str(x)))

car_counts = df1.groupby(['County', 'City']).size().reset_index(name='Car Count')

In [ ]:
# Group by County and City and count the number of cars
car_counts = df1.groupby(['County', 'City']).size().reset_index(name='Car Count')

county_counts = car_counts.groupby('County')['Car Count'].sum().reset_index()

county_counts = county_counts.sort_values(by='Car Count', ascending=False).reset_index()

county_counts = county_counts.drop(['index'], axis=1)

county_counts

          County  Car Count
0           King      99076
1      Snohomish      22643
2         Pierce      14932
3          Clark      11328
4       Thurston       6969
5         Kitsap       6303
6        Spokane       5015
7        Whatcom       4602
8         Benton       2351
9         Skagit       2076
10        Island       2021
11        Chelan       1147
12        Yakima       1128
13       Clallam       1127
14     Jefferson       1057
15       Cowlitz        995
16      San Juan        986
17         Mason        891
18         Lewis        843
19  Grays Harbor        690
20      Kittitas        686
21         Grant        649
22      Franklin        639
23   Walla Walla        469
24       Douglas        385
25       Whitman        371
26     Klickitat        314
27      Okanogan        287
28       Stevens        237
29       Pacific        215
30      Skamania        200
31        Asotin         80
32     Wahkiakum         64
33  Pend Oreille         57
34         Adams         55
35       Lincoln         51
36         Ferry         35
37      Columbia         13
38      Garfield          2

In [ ]:
# Example: Select rows by index
countycounts_selected_rows = county_counts.loc[[0, 1, 2, 3, 4, 34, 35, 36, 37, 38]]
countycounts_selected_rows = countycounts_selected_rows.to_latex(index=False, escape=False, column_format='||c c||', caption='Electric Vehicle Population Dataset.', label='table:1')
print(countycounts_selected_rows)

\begin{table}
\caption{Electric Vehicle Population Dataset.}
\label{table:1}
\begin{tabular}{||c c||}
\toprule
County & Car Count \\
\midrule
King & 99076 \\
Snohomish & 22643 \\
Pierce & 14932 \\
Clark & 11328 \\
Thurston & 6969 \\
Adams & 55 \\
Lincoln & 51 \\
Ferry & 35 \\
Columbia & 13 \\
Garfield & 2 \\
\bottomrule
\end{tabular}
\end{table}

In [ ]:
df_washington = pd.read_csv('/content/washpop.csv')

df_washington = df_washington.drop(columns=['name', 'pop2020', 'year', 'fips', 'state', 'stateCode', 'growthSince2020', 'slug', 'rank', 'densityMi', 'areaMi'])

df_washington['county'] = df_washington['county'].str.replace(' County', '', regex=False)

df_washington

    pop2024        county  landArea      density
0   2277449          King      2116  1076.299149
1    930913        Pierce      1668   558.101319
2    849070     Snohomish      2087   406.837566
3    553170       Spokane      1764   313.588435
4    525563         Clark       628   836.883758
5    299367      Thurston       723   414.062241
6    277503        Kitsap       395   702.539241
7    256267        Yakima      4295    59.666356
8    233240       Whatcom      2108   110.645161
9    217609        Benton      1700   128.005294
10   131512        Skagit      1730    76.018497
11   113664       Cowlitz      1141    99.617879
12   103776         Grant      2680    38.722388
13    99486      Franklin      1242    80.101449
14    86951         Lewis      2403    36.184353
15    85852        Island       208   412.750000
16    79956        Chelan      2921    27.372818
17    77548       Clallam      1739    44.593445
18    77539  Grays Harbor      1901    40.788532
19    68607         Mason       960    71.465625
20    61283   Walla Walla      1270    48.254331
21    49391       Stevens      2477    19.939847
22    48445       Whitman      2159    22.438629
23    45894      Kittitas      2297    19.979974
24    45373       Douglas      1819    24.943925
25    43964      Okanogan      5266     8.348652
26    33858     Jefferson      1804    18.768293
27    24305       Pacific       933    26.050375
28    23875     Klickitat      1872    12.753739
29    22562        Asotin       636    35.474843
30    20742         Adams      1925    10.775065
31    18460      San Juan       174   106.091954
32    14584  Pend Oreille      1400    10.417143
33    12825      Skamania      1658     7.735223
34    11863       Lincoln      2311     5.133276
35     7526         Ferry      2203     3.416251
36     4842     Wahkiakum       263    18.410646
37     4080      Columbia       869     4.695052
38     2369      Garfield       711     3.331927

In [ ]:
# Example: Select rows by index
df_washington_selected_rows = df_washington.loc[[0, 1, 2, 3, 4, 34, 35, 36, 37, 38]]
df_washington_selected_rows = df_washington_selected_rows.to_latex(index=False, escape=False, column_format='||c c||', caption='County Population and Density Dataset')
print(df_washington_selected_rows)

\begin{table}
\caption{County Population and Density Dataset}
\begin{tabular}{||c c||}
\toprule
pop2024 & county & landArea & density \\
\midrule
2277449 & King & 2116 & 1076.299149 \\
930913 & Pierce & 1668 & 558.101319 \\
849070 & Snohomish & 2087 & 406.837566 \\
553170 & Spokane & 1764 & 313.588435 \\
525563 & Clark & 628 & 836.883758 \\
11863 & Lincoln & 2311 & 5.133276 \\
7526 & Ferry & 2203 & 3.416251 \\
4842 & Wahkiakum & 263 & 18.410646 \\
4080 & Columbia & 869 & 4.695052 \\
2369 & Garfield & 711 & 3.331927 \\
\bottomrule
\end{tabular}
\end{table}

In [ ]:
df_countyGDP = pd.read_csv('/content/washGDP.csv')

df_countyGDP = df_countyGDP.drop(index=0).reset_index(drop=True)

df_countyGDP['County'] = df_countyGDP['County'].str.replace('_', ' ', regex=False)

df_countyGDP.rename(columns={'2020': '2020 GDP'}, inplace=True)

df_countyGDP = df_countyGDP.sort_values(by='Rank', ascending=True).reset_index()

df_countyGDP = df_countyGDP.drop(columns=['Rank', '2022', '2019', '2021', '2020 change', '2021 Change', '2022 Change', 'Rank in State', 'index'])

df_countyGDP

          County   2020 GDP
0           King  329239691
1      Snohomish   45864728
2         Pierce   44792744
3        Spokane   26628547
4          Clark   22164411
5       Thurston   13747480
6        Whatcom   14158405
7         Kitsap   12734085
8         Benton   11478886
9         Yakima   10523373
10        Skagit    6679499
11         Grant    5762071
12       Cowlitz    5302398
13        Chelan    4540557
14      Franklin    3925358
15         Lewis    3423053
16        Island    3307517
17   Walla Walla    3238194
18       Whitman    2593106
19       Clallam    2501467
20  Grays Harbor    2430348
21       Douglas    1866829
22      Kittitas    1812988
23         Mason    1587194
24     Klickitat    1588044
25      Okanogan    1464428
26     Jefferson    1079300
27       Stevens    1087448
28      San Juan     775348
29       Pacific     727340
30        Asotin     657568
31  Pend Oreille     486306
32       Lincoln     489660
33      Columbia     333032
34      Skamania     270333
35         Ferry     190828
36      Garfield     173024
37     Wahkiakum      99504

In [ ]:
df_chargingstations = pd.read_csv('/content/chargingstations.csv', delimiter=';', encoding='ISO-8859-1')

df_chargingstations = df_chargingstations.drop(columns=['Station Name', 'Street Address', 'ZIP', 'EV Network', 'EV Connector Types', 'Access Code', 'Access Detail Code', 'Facility Type'])

df_chargingstations = df_chargingstations[df_chargingstations['State'] == 'WA']

df_chargingstations['Total Chargers'] = df_chargingstations['EV Level1 EVSE Num'].fillna(0) + df_chargingstations['EV Level2 EVSE Num'].fillna(0) + df_chargingstations['EV DC Fast Count'].fillna(0)

df_chargingstations = df_chargingstations.drop(columns=['EV Level1 EVSE Num', 'EV Level2 EVSE Num', 'EV DC Fast Count'])

df_chargingstations = df_chargingstations.groupby('City', as_index=False).agg({'Total Chargers': 'sum'})

citiesInWA = car_counts

citiesInWA.drop(columns=['Car Count'])

county_chargers = pd.merge(citiesInWA, df_chargingstations, on='City', how='left')

county_chargers = county_chargers.groupby('County', as_index=False).agg({'Total Chargers': 'sum'})

county_chargers = county_chargers.sort_values(by='Total Chargers', ascending=False).reset_index()

county_chargers = county_chargers.drop(['index'], axis=1)

county_chargers

          County  Total Chargers
0           King          2925.0
1      Snohomish           455.0
2         Pierce           455.0
3        Spokane           287.0
4         Kitsap           270.0
5          Clark           249.0
6       Thurston           232.0
7         Skagit           207.0
8         Benton           141.0
9        Whatcom           124.0
10        Chelan           105.0
11        Yakima           103.0
12         Lewis            92.0
13       Clallam            86.0
14      Kittitas            74.0
15     Jefferson            66.0
16  Grays Harbor            51.0
17   Walla Walla            48.0
18      San Juan            43.0
19      Skamania            35.0
20         Grant            33.0
21       Cowlitz            33.0
22      Okanogan            32.0
23       Whitman            25.0
24      Franklin            23.0
25        Island            21.0
26         Mason            16.0
27       Pacific            15.0
28       Lincoln            12.0
29       Douglas            10.0
30         Adams             9.0
31     Klickitat             8.0
32       Stevens             7.0
33      Columbia             5.0
34     Wahkiakum             3.0
35  Pend Oreille             2.0
36        Asotin             2.0
37      Garfield             0.0
38         Ferry             0.0

In [ ]:
# Renaming the 'county' column in df_washington to match 'County'
df_washington = df_washington.rename(columns={'county': 'County'})

# First, merge county_counts with df_countyGDP
merged_df = pd.merge(df_countyGDP, county_counts, on='County', how='left')

# Then merge the result with df_washington
merged_df = pd.merge(merged_df, df_washington, on='County', how='left')

# Then merge the result with df_washington
merged_df = pd.merge(merged_df, county_chargers, on='County', how='left')

# Fill missing values in 'Car_Count' with 0
merged_df['Car Count'] = merged_df['Car Count'].fillna(0)

# Create the final ML_TABLE with the desired columns
ML_TABLE = merged_df[['County', 'Car Count', 'Total Chargers', '2020 GDP', 'pop2020', 'landArea', 'density']]

ML_TABLE = ML_TABLE.rename(columns={'2020 GDP': 'GDP'})

ML_TABLE = ML_TABLE.rename(columns={'Car Count': 'Number of Vehicles'})

ML_TABLE = ML_TABLE.rename(columns={'pop2020': 'Population'})

ML_TABLE = ML_TABLE.rename(columns={'landArea': 'Land Area'})

ML_TABLE = ML_TABLE.rename(columns={'density': 'Population Density'})

ML_TABLE = ML_TABLE.sort_values('Number of Vehicles', ascending=False)

# Display the ML_TABLE
ML_TABLE.fillna(0, inplace=True)  # Fill NaN with 0

# Add a new column 'State' and set its value to 'Washington' for all rows
ML_TABLE['State'] = 'Washington'

# Display the updated ML_TABLE
ML_TABLE

,County,Number of Vehicles,Total Chargers,GDP,Population,Land Area,Population Density,State
0,King,99076,2925.0,329239691,2274282,2116,1076.299149,Washington
1,Snohomish,22643,455.0,45864728,829933,2087,406.837566,Washington
2,Pierce,14932,455.0,44792744,923589,1668,558.101319,Washington
4,Clark,11328,249.0,22164411,505338,628,836.883758,Washington
5,Thurston,6969,232.0,13747480,295998,723,414.062241,Washington
7,Kitsap,6303,270.0,12734085,275823,395,702.539241,Washington
3,Spokane,5015,287.0,26628547,541175,1764,313.588435,Washington
6,Whatcom,4602,124.0,14158405,227449,2108,110.645161,Washington
8,Benton,2351,141.0,11478886,207419,1700,128.005294,Washington
10,Skagit,2076,207.0,6679499,129902,1730,76.018497,Washington
16,Island,2021,21.0,3307517,86998,208,412.750000,Washington
13,Chelan,1147,105.0,4540557,79238,2921,27.372818,Washington
9,Yakima,1128,103.0,10523373,256733,4295,59.666356,Washington
19,Clallam,1127,86.0,2501467,77367,1739,44.593445,Washington
26,Jefferson,1057,66.0,1079300,33061,1804,18.768293,Washington
12,Cowlitz,995,33.0,5302398,111014,1141,99.617879,Washington
28,San Juan,986,43.0,775348,17826,174,106.091954,Washington
23,Mason,891,16.0,1587194,66034,960,71.465625,Washington
15,Lewis,843,92.0,3423053,82553,2403,36.184353,Washington
20,Grays Harbor,690,51.0,2430348,75855,1901,40.788532,Washington
22,Kittitas,686,74.0,1812988,44599,2297,19.979974,Washington
11,Grant,649,33.0,5762071,99441,2680,38.722388,Washington
14,Franklin,639,23.0,3925358,97150,1242,80.101449,Washington
17,Walla Walla,469,48.0,3238194,62623,1270,48.254331,Washington
21,Douglas,385,10.0,1866829,43029,1819,24.943925,Washington
18,Whitman,371,25.0,2593106,47807,2159,22.438629,Washington
24,Klickitat,314,8.0,1588044,22814,1872,12.753739,Washington
25,Okanogan,287,32.0,1464428,42139,5266,8.348652,Washington
27,Stevens,237,7.0,1087448,46591,2477,19.939847,Washington
29,Pacific,215,15.0,727340,23495,933,26.050375,Washington
34,Skamania,200,35.0,270333,12041,1658,7.735223,Washington
30,Asotin,80,2.0,657568,22324,636,35.474843,Washington
37,Wahkiakum,64,3.0,99504,4448,263,18.410646,Washington
31,Pend Oreille,57,2.0,486306,13502,1400,10.417143,Washington
32,Lincoln,51,12.0,489660,10928,2311,5.133276,Washington
35,Ferry,35,0.0,190828,7198,2203,3.416251,Washington
33,Columbia,13,5.0,333032,3949,869,4.695052,Washington
36,Garfield,2,0.0,173024,2294,711,3.331927,Washington

In [ ]:
df_california = pd.read_csv('/content/New_ZEV_Sales_Last_updated_11-19-2024_ada.csv')

df_california[['Data_Year', 'Quarter', 'County', 'FUEL_TYPE', 'MAKE', 'MODEL', 'Number of Vehicles']] = df_california['Data_Year;Quarter;County;FUEL_TYPE;MAKE;MODEL;Number of Vehicles'].str.split(';', expand=True)

df_california = df_california.drop(columns=['Data_Year;Quarter;County;FUEL_TYPE;MAKE;MODEL;Number of Vehicles'])

df_california = df_california.drop(columns=['Data_Year', 'Quarter', 'MAKE', 'MODEL'])

df_california['Number of Vehicles'] = pd.to_numeric(df_california['Number of Vehicles'], errors='coerce')

CA_vehicle_totals = df_california.groupby('County')['Number of Vehicles'].sum()

CA_vehicle_totals = CA_vehicle_totals[CA_vehicle_totals.index != "Out Of State"]

CA_vehicle_totals_sorted = CA_vehicle_totals.sort_values(ascending=False)

CA_vehicle_totals_sorted

County
Los Angeles        581479
Orange             263287
Santa Clara        223206
San Diego          175122
Alameda            134796
Riverside           84558
San Mateo           81051
Contra Costa        76935
San Bernardino      66257
San Francisco       52093
Sacramento          51968
Ventura             44484
Marin               27367
Sonoma              23175
San Joaquin         23057
Placer              20762
Fresno              18370
Solano              15090
Santa Barbara       14933
Santa Cruz          12464
Kern                12209
Monterey             9911
San Luis Obispo      9856
Stanislaus           8497
Yolo                 8085
El Dorado            7617
Napa                 6768
Tulare               4321
Merced               2929
Nevada               2596
Butte                2557
Shasta               2198
Humboldt             2150
San Benito           2110
Madera               1909
Mendocino            1644
Imperial             1578
Kings                1355
Sutter               1351
Yuba                 1001
Calaveras             769
Tuolumne              708
Lake                  705
Amador                541
Tehama                411
Siskiyou              284
Inyo                  237
Mono                  212
Mariposa              211
Glenn                 182
Del Norte             155
Plumas                149
Colusa                125
Trinity                77
Lassen                 68
Alpine                 41
Sierra                 19
Modoc                  12
Name: Number of Vehicles, dtype: int64

In [ ]:
california_charger = pd.read_csv('/content/EV_Chargers_Last_updated_08-26-2024_ada.csv')

california_charger[['County', 'Public Level 1', 'Shared Private Level 1', 'Public Level 2', 'Shared Private Level 2', 'Public DC Fast', 'Shared Private DC Fast', 'Total']] = california_charger['County;Public Level 1;Shared Private Level 1;Public Level 2;Shared Private Level 2;Public DC Fast;Shared Private DC Fast;Total'].str.split(';', expand=True)

california_charger = california_charger.drop(columns=['County;Public Level 1;Shared Private Level 1;Public Level 2;Shared Private Level 2;Public DC Fast;Shared Private DC Fast;Total'])

california_charger = california_charger.drop(columns=['Public Level 1', 'Shared Private Level 1', 'Public Level 2', 'Shared Private Level 2', 'Public DC Fast', 'Shared Private DC Fast'])

california_charger['Total'] = pd.to_numeric(california_charger['Total'], errors='coerce')

# Sort the DataFrame by the 'Total' column in descending order
california_charger = california_charger.sort_values('Total', ascending=False)

california_charger = california_charger.drop(index=58)

california_charger

             County  Total
18      Los Angeles  60698
42      Santa Clara  23365
36        San Diego  10982
29           Orange   8522
40        San Mateo   6994
0           Alameda   6478
33       Sacramento   3984
32        Riverside   3206
35   San Bernardino   2911
37    San Francisco   2853
6      Contra Costa   2384
9            Fresno   1879
55          Ventura   1531
48           Sonoma   1376
20            Marin   1290
14             Kern   1282
38      San Joaquin   1173
41    Santa Barbara   1105
30           Placer   1072
39  San Luis Obispo   1063
47           Solano    970
56             Yolo    810
27             Napa    775
26         Monterey    769
43       Santa Cruz    542
53           Tulare    488
44           Shasta    392
49       Stanislaus    379
22        Mendocino    329
8         El Dorado    326
23           Merced    322
19           Madera    317
15            Kings    298
11         Humboldt    275
3             Butte    259
28           Nevada    184
51           Tehama    156
21         Mariposa    145
46         Siskiyou    114
57             Yuba    112
13             Inyo    110
12         Imperial    108
54         Tuolumne    100
7         Del Norte     83
25             Mono     81
2            Amador     72
34       San Benito     65
5            Colusa     53
16             Lake     50
50           Sutter     47
4         Calaveras     41
10            Glenn     33
52          Trinity     19
17           Lassen     19
31           Plumas     16
1            Alpine     12
24            Modoc     12
45           Sierra      3

In [ ]:
# Example: Select rows by index
california_charger_selected_rows = california_charger.loc[[0, 1, 2, 3, 4, 53, 54, 55, 56, 57]]
california_charger_selected_rows = california_charger_selected_rows.to_latex(index=False, escape=False, column_format='||c c||', caption='2023 Texas County GDP')
print(california_charger_selected_rows)

\begin{table}
\caption{2023 Texas County GDP}
\begin{tabular}{||c c||}
\toprule
County & Total \\
\midrule
Alameda & 6478 \\
Alpine & 12 \\
Amador & 72 \\
Butte & 259 \\
Calaveras & 41 \\
Tulare & 488 \\
Tuolumne & 100 \\
Ventura & 1531 \\
Yolo & 810 \\
Yuba & 112 \\
\bottomrule
\end{tabular}
\end{table}

In [ ]:
california_population = pd.read_csv('/content/californiapop.csv')

california_population = california_population.drop(columns=['name', 'pop2020', 'year', 'fips', 'state', 'stateCode', 'growthSince2020', 'slug', 'rank', 'densityMi', 'areaMi'])

california_population['county'] = california_population['county'].str.replace(' County', '', regex=False)

california_population

    pop2024           county  landArea       density
0   9606925      Los Angeles      4060   2366.237685
1   3262770        San Diego      4210    775.004751
2   3121138           Orange       793   3935.861286
3   2510643        Riverside      7209    348.265085
4   2196314   San Bernardino     20068    109.443592
5   1876849      Santa Clara      1291   1453.794733
6   1616117          Alameda       737   2192.831750
7   1584196       Sacramento       965   1641.653886
8   1153031     Contra Costa       717   1608.132497
9   1018965           Fresno      5958    171.024673
10   910889             Kern      8135    111.971604
11   826309          Ventura      1841    448.837045
12   810202    San Francisco        47  17238.340426
13   807637      San Joaquin      1392    580.198994
14   723777        San Mateo       449   1611.975501
15   551634       Stanislaus      1496    368.739305
16   481052           Tulare      4824     99.720564
17   480955           Sonoma      1575    305.368254
18   449551           Solano       822    546.899027
19   438599    Santa Barbara      2734    160.423921
20   429048           Placer      1407    304.938166
21   428562         Monterey      3282    130.579525
22   293630           Merced      1938    151.511868
23   281232  San Luis Obispo      3301     85.196001
24   258854       Santa Cruz       445    581.694382
25   252660            Marin       520    485.884615
26   219070             Yolo      1013    216.258638
27   206975            Butte      1636    126.512836
28   191643        El Dorado      1708    112.203162
29   179795           Shasta      3776     47.615201
30   179174         Imperial      4176     42.905651
31   165387           Madera      2137     77.392139
32   152377            Kings      1391    109.544932
33   133026         Humboldt      3568     37.283072
34   132062             Napa       752    175.614362
35   101673           Nevada       958    106.130480
36    97327           Sutter       603    161.404643
37    88209        Mendocino      3507     25.152267
38    87091             Yuba       632    137.802215
39    68707       San Benito      1389     49.465083
40    67584             Lake      1255     53.851793
41    64493           Tehama      2949     21.869447
42    53821         Tuolumne      2221     24.232778
43    46574        Calaveras      1020     45.660784
44    42129           Amador       595     70.805042
45    42024         Siskiyou      6279      6.692785
46    27898            Glenn      1314     21.231355
47    27702           Lassen      4541      6.100418
48    26066        Del Norte      1006     25.910537
49    22165           Colusa      1151     19.257168
50    18819           Plumas      2553      7.371328
51    18312             Inyo     10197      1.795822
52    16785         Mariposa      1449     11.583851
53    15562          Trinity      3179      4.895250
54    13130             Mono      3049      4.306330
55     8381            Modoc      3948      2.122847
56     3178           Sierra       953      3.334732
57     1092           Alpine       738      1.479675

In [ ]:
california_gdp = pd.read_csv('/content/gdpcalifornia.csv')

california_gdp[['California', '3.248.656.553']] = california_gdp['California;3.248.656.553'].str.split(';', expand=True)

california_gdp = california_gdp.drop(columns=['California;3.248.656.553'])

california_gdp = california_gdp.rename(columns={"California": "County", "3.248.656.553": "GDP"})

california_gdp['GDP'] = california_gdp['GDP'].str.replace('.', '', regex=False)

california_gdp

             County        GDP
0           Alameda  150532046
1            Alpine     105610
2            Amador    1659330
3             Butte    9278380
4         Calaveras    1472506
5            Colusa    1609218
6      Contra Costa   78357593
7         Del Norte     844062
8         El Dorado    8833331
9            Fresno   47612742
10            Glenn    1031970
11         Humboldt    5872356
12         Imperial   10467574
13             Inyo    1141849
14             Kern   46941848
15            Kings    7041297
16             Lake    1954710
17           Lassen    1142546
18      Los Angeles  801967353
19           Madera    6226914
20            Marin   30661017
21         Mariposa     786148
22        Mendocino    3667396
23           Merced    9548937
24            Modoc     554727
25             Mono    1178510
26         Monterey   28980213
27             Napa   11412110
28           Nevada    4747160
29           Orange  273063592
30           Placer   27022666
31           Plumas    1035904
32        Riverside   98880553
33       Sacramento  102387018
34       San Benito    2273410
35   San Bernardino  102307449
36        San Diego  261671687
37    San Francisco  237017759
38      San Joaquin   33097405
39  San Luis Obispo   18023027
40        San Mateo  186334708
41    Santa Barbara   31996811
42      Santa Clara  390234709
43       Santa Cruz   16488399
44           Shasta    8742908
45           Sierra      98012
46         Siskiyou    1849450
47           Solano   29643413
48           Sonoma   31011472
49       Stanislaus   24067824
50           Sutter    3915978
51           Tehama    2135028
52          Trinity     402737
53           Tulare   18824792
54         Tuolumne    2610180
55          Ventura   53629861
56             Yolo   15555485
57             Yuba    3373337

In [ ]:
california_population
california_charger
california_gdp
CA_vehicle_totals_sorted

# Renaming the 'county' column in df_washington to match 'County'
california_population = california_population.rename(columns={'county': 'County'})

# First, merge county_counts with df_countyGDP
merged_df = pd.merge(california_gdp, CA_vehicle_totals_sorted, on='County', how='left')

# Then merge the result with df_washington
merged_df = pd.merge(merged_df, california_population, on='County', how='left')

# Then merge the result with df_washington
merged_df = pd.merge(merged_df, california_charger, on='County', how='left')

# Create the final ML_TABLE with the desired columns
ML_TABLE2 = merged_df[['County', 'Number of Vehicles', 'Total', 'GDP', 'pop2024', 'landArea', 'density']]

ML_TABLE2 = ML_TABLE2.sort_values('Number of Vehicles', ascending=False)

ML_TABLE2 = ML_TABLE2.rename(columns={'Total': 'Total Chargers'})

ML_TABLE2 = ML_TABLE2.rename(columns={'pop2024': 'Population'})

ML_TABLE2 = ML_TABLE2.rename(columns={'landArea': 'Land Area'})

ML_TABLE2 = ML_TABLE2.rename(columns={'density': 'Population Density'})

ML_TABLE2

,County,Number of Vehicles,Total Chargers,GDP,Population,Land Area,Population Density
18,Los Angeles,581479,60698,801967353,9606925,4060,2366.237685
29,Orange,263287,8522,273063592,3121138,793,3935.861286
42,Santa Clara,223206,23365,390234709,1876849,1291,1453.794733
36,San Diego,175122,10982,261671687,3262770,4210,775.004751
0,Alameda,134796,6478,150532046,1616117,737,2192.831750
32,Riverside,84558,3206,98880553,2510643,7209,348.265085
40,San Mateo,81051,6994,186334708,723777,449,1611.975501
6,Contra Costa,76935,2384,78357593,1153031,717,1608.132497
35,San Bernardino,66257,2911,102307449,2196314,20068,109.443592
37,San Francisco,52093,2853,237017759,810202,47,17238.340426
33,Sacramento,51968,3984,102387018,1584196,965,1641.653886
55,Ventura,44484,1531,53629861,826309,1841,448.837045
20,Marin,27367,1290,30661017,252660,520,485.884615
48,Sonoma,23175,1376,31011472,480955,1575,305.368254
38,San Joaquin,23057,1173,33097405,807637,1392,580.198994
30,Placer,20762,1072,27022666,429048,1407,304.938166
9,Fresno,18370,1879,47612742,1018965,5958,171.024673
47,Solano,15090,970,29643413,449551,822,546.899027
41,Santa Barbara,14933,1105,31996811,438599,2734,160.423921
43,Santa Cruz,12464,542,16488399,258854,445,581.694382
14,Kern,12209,1282,46941848,910889,8135,111.971604
26,Monterey,9911,769,28980213,428562,3282,130.579525
39,San Luis Obispo,9856,1063,18023027,281232,3301,85.196001
49,Stanislaus,8497,379,24067824,551634,1496,368.739305
56,Yolo,8085,810,15555485,219070,1013,216.258638
8,El Dorado,7617,326,8833331,191643,1708,112.203162
27,Napa,6768,775,11412110,132062,752,175.614362
53,Tulare,4321,488,18824792,481052,4824,99.720564
23,Merced,2929,322,9548937,293630,1938,151.511868
28,Nevada,2596,184,4747160,101673,958,106.130480
3,Butte,2557,259,9278380,206975,1636,126.512836
44,Shasta,2198,392,8742908,179795,3776,47.615201
11,Humboldt,2150,275,5872356,133026,3568,37.283072
34,San Benito,2110,65,2273410,68707,1389,49.465083
19,Madera,1909,317,6226914,165387,2137,77.392139
22,Mendocino,1644,329,3667396,88209,3507,25.152267
12,Imperial,1578,108,10467574,179174,4176,42.905651
15,Kings,1355,298,7041297,152377,1391,109.544932
50,Sutter,1351,47,3915978,97327,603,161.404643
57,Yuba,1001,112,3373337,87091,632,137.802215
4,Calaveras,769,41,1472506,46574,1020,45.660784
54,Tuolumne,708,100,2610180,53821,2221,24.232778
16,Lake,705,50,1954710,67584,1255,53.851793
2,Amador,541,72,1659330,42129,595,70.805042
51,Tehama,411,156,2135028,64493,2949,21.869447
46,Siskiyou,284,114,1849450,42024,6279,6.692785
13,Inyo,237,110,1141849,18312,10197,1.795822
25,Mono,212,81,1178510,13130,3049,4.306330
21,Mariposa,211,145,786148,16785,1449,11.583851
10,Glenn,182,33,1031970,27898,1314,21.231355
7,Del Norte,155,83,844062,26066,1006,25.910537
31,Plumas,149,16,1035904,18819,2553,7.371328
5,Colusa,125,53,1609218,22165,1151,19.257168
52,Trinity,77,19,402737,15562,3179,4.895250
17,Lassen,68,19,1142546,27702,4541,6.100418
1,Alpine,41,12,105610,1092,738,1.479675
45,Sierra,19,3,98012,3178,953,3.334732
24,Modoc,12,12,554727,8381,3948,2.122847

In [ ]:
ML_TABLE = pd.concat([ML_TABLE, ML_TABLE2], ignore_index=True)

ML_TABLE = ML_TABLE.sort_values('Number of Vehicles', ascending=False)

ML_TABLE

,County,Number of Vehicles,Total Chargers,GDP,Population,Land Area,Population Density
38,Los Angeles,581479.0,60698.0,801967353,9606925,4060,2366.237685
39,Orange,263287.0,8522.0,273063592,3121138,793,3935.861286
40,Santa Clara,223206.0,23365.0,390234709,1876849,1291,1453.794733
41,San Diego,175122.0,10982.0,261671687,3262770,4210,775.004751
42,Alameda,134796.0,6478.0,150532046,1616117,737,2192.831750
...,...,...,...,...,...,...,...
21,Skamania,0.0,0.0,270333,12041,1658,7.735223
20,Ferry,0.0,0.0,190828,7198,2203,3.416251
19,Garfield,0.0,0.0,173024,2294,711,3.331927
18,San Juan,0.0,0.0,775348,17826,174,106.091954
29,Spokane,0.0,0.0,26628547,541175,1764,313.588435

In [ ]:
florida_population = pd.read_csv('/content/Floridapop.csv')

florida_population = florida_population.drop(columns=['name', 'pop2020', 'year', 'fips', 'state', 'stateCode', 'growthSince2020', 'slug', 'rank', 'densityMi', 'areaMi'])

florida_population['county'] = florida_population['county'].str.replace(' County', '', regex=False)

florida_population

    pop2024        county  landArea      density
0   2700678    Miami-Dade      1900  1421.409474
1   1978173       Broward      1203  1644.366584
2   1557655  Hillsborough      1023  1522.634409
3   1547735    Palm Beach      1964   788.052444
4   1491071        Orange       903  1651.241417
..      ...           ...       ...          ...
62    13475       Calhoun       567    23.765432
63    13109        Glades       807    16.244114
64    12696      Franklin       545    23.295413
65     8379     Lafayette       543    15.430939
66     7799       Liberty       836     9.328947

[67 rows x 4 columns]

In [ ]:
florida_gdp = pd.read_csv('/content/gdpflorida.csv')

florida_gdp[['Florida', '2023']] = florida_gdp['Florida;2023'].str.split(';', expand=True)

florida_gdp = florida_gdp.drop(columns=['Florida;2023'])

florida_gdp = florida_gdp.rename(columns={"Florida": "County", "2023": "GDP"})

florida_gdp['GDP'] = florida_gdp['GDP'].str.replace('.', '', regex=False)

florida_gdp

        County       GDP
0      Alachua  16176855
1        Baker    774660
2          Bay  10140163
3     Bradford    688898
4      Brevard  32780628
..         ...       ...
62       Union    394035
63     Volusia  21986706
64     Wakulla    872371
65      Walton   4720447
66  Washington    701303

[67 rows x 2 columns]

In [ ]:
florida_fips = pd.read_csv('/content/Floridapop.csv')

florida_fips = florida_fips.drop(columns=['name', 'pop2020', 'year', 'pop2024', 'state', 'stateCode', 'growthSince2020', 'slug', 'rank', 'densityMi', 'areaMi', 'landArea', 'density'])

florida_fips

     fips               county
0   12086    Miami-Dade County
1   12011       Broward County
2   12057  Hillsborough County
3   12099    Palm Beach County
4   12095        Orange County
..    ...                  ...
62  12013       Calhoun County
63  12043        Glades County
64  12037      Franklin County
65  12067     Lafayette County
66  12077       Liberty County

[67 rows x 2 columns]

In [ ]:
florida_chargers = pd.read_csv('/content/Alternative_Fueling_Stations_-6669030252532885733.csv')

florida_chargers = florida_chargers.drop(columns=[
    'OBJECTID', 'access_code', 'access_days_time', 'access_detail_code', 'cards_accepted', 'date_last_confirmed', 'expected_date', 'fuel_type_code', 'groups_with_access_code', 'id', 'bd_blends_fr',
    'groups_with_access_code_fr', 'ev_pricing_fr', 'nps_unit_name', 'access_days_time_fr', 'intersection_directions_fr', 'federal_agency_id', 'federal_agency_code', 'federal_agency_name', 'ev_network_ids_station',
    'ev_network_ids_posts', 'x', 'y', 'station_phone', 'updated_at', 'lng_vehicle_class', 'lpg_nozzle_types', 'lpg_primary', 'ng_fill_type_code', 'ng_psi', 'ng_vehicle_class', 'rd_blended_with_biodiesel',
    'rd_blends', 'rd_blends_fr', 'rd_max_biodiesel_level', 'maximum_vehicle_class', 'open_date', 'owner_type_code', 'restricted_access', 'status_code', 'funding_sources', 'facility_type', 'geocode_status',
    'latitude', 'ev_other_evse', 'ev_pricing', 'ev_renewable_source', 'ev_workplace_charging', 'hy_is_retail',
    'hy_pressures', 'hy_standards', 'hy_status_link', 'longitude', 'country', 'lpg_nozzle_types', 'intersection_directions', 'plus4', 'street_address', 'zip', 'bd_blends', 'cng_dispenser_num', 'cng_fill_type_code',
    'cng_has_rng', 'cng_psi', 'cng_renewable_source', 'cng_total_compression', 'cng_total_storage', 'e85_blender_pump', 'e85_other_ethanol_blends', 'ev_connector_types', 'ev_dc_fast_num',
    'ev_level1_evse_num', 'ev_level2_evse_num', 'ev_network', 'ev_network_web', 'lng_has_rng', 'lng_renewable_source', 'cng_vehicle_class', 'ev_connector_types'])

florida_chargers = florida_chargers[florida_chargers['state'] == "FL"]

florida_cities = pd.read_csv('/content/Copy of Spreadsheet List of All cities in Florida export 2024-12-10 02-57-35.csv')

florida_cities = florida_cities.drop(columns=['state_id', 'state_name', 'lat', 'lng', 'population', 'type', 'name_ascii'])

florida_chargers = pd.merge(florida_chargers, florida_cities, left_on='city', right_on='name', how='left')

florida_chargers.dropna(inplace=True)

florida_chargers = florida_chargers.drop(columns=['name', 'state'])

florida_chargers = pd.merge(florida_chargers, florida_fips, left_on='county_fips', right_on='fips', how='left')

florida_chargers = florida_chargers.drop(columns=['county_fips', 'city'])

# Group the dataframe by 'county'
florida_chargers = florida_chargers.groupby('county')

# Calculate the total number of rows for each county
florida_chargers = florida_chargers.size().reset_index(name='total_rows')

# Drop the 'station_name' column
florida_chargers = florida_chargers.drop('station_name', axis=1, errors='ignore')

# Drop duplicate rows
florida_chargers = florida_chargers.drop_duplicates()

florida_chargers['county'] = florida_chargers['county'].str.replace(' County', '', regex=False)

florida_chargers = florida_chargers.rename(columns={'county': 'County'})

florida_chargers

          County  total_rows
0        Alachua           2
1        Brevard           3
2        Broward           2
3          Duval           6
4       Escambia           2
5   Hillsborough           5
6            Lee           1
7         Martin           1
8     Miami-Dade           2
9       Okaloosa           2
10        Orange           9
11    Palm Beach           1
12      Pinellas           3
13    Santa Rosa           1
14      Sarasota           1
15      Seminole           2
16     St. Lucie           1

In [ ]:
df_florida = pd.read_csv('/content/fl_ev_registrations_public.csv')

df_florida = df_florida.drop(columns=['DMV ID', 'DMV Snapshot (Date)', 'Vehicle Name', 'Registration Valid Date', 'Registration Expiration Date', 'Technology'])

df_florida = df_florida.groupby('County')

df_florida = df_florida.size().reset_index(name='total_rows')

df_florida['County'] = df_florida['County'].str.replace('Dade', 'Miami-Dade', regex=False)

df_florida = df_florida[df_florida["County"] != "Unknown"]

df_florida

        County  total_rows
0      Alachua         335
1        Baker           3
2          Bay         141
3     Bradford          10
4      Brevard         821
..         ...         ...
58      Taylor           1
59     Volusia         495
60     Wakulla          12
61      Walton          96
62  Washington           5

[63 rows x 2 columns]

In [ ]:
florida_population
florida_chargers
florida_gdp
df_florida

# Renaming the 'county' column in df_washington to match 'County'
florida_population = florida_population.rename(columns={'county': 'County'})

# First, merge county_counts with df_countyGDP
merged_fl = pd.merge(florida_gdp, df_florida, on='County', how='left')

# Renaming the 'county' column in df_washington to match 'County'
merged_fl = merged_fl.rename(columns={'total_rows': 'Number of Vehicles'})

# Then merge the result with df_washington
merged_fl = pd.merge(merged_fl, florida_population, on='County', how='left')

# Then merge the result with df_washington
merged_fl = pd.merge(merged_fl, florida_chargers, on='County', how='left')

merged_fl = merged_fl.rename(columns={'total_rows': 'Total Chargers'})

# Create the final ML_TABLE with the desired columns
ML_TABLE2 = merged_fl[['County', 'GDP', 'Number of Vehicles', 'pop2024', 'landArea', 'density', 'Total Chargers']]

ML_TABLE2 = ML_TABLE2.sort_values('Number of Vehicles', ascending=False)

ML_TABLE2 = ML_TABLE2.rename(columns={'pop2024': 'Population'})

ML_TABLE2 = ML_TABLE2.rename(columns={'landArea': 'Land Area'})

ML_TABLE2 = ML_TABLE2.rename(columns={'density': 'Population Density'})

ML_TABLE2.fillna(0, inplace=True)

ML_TABLE2

,County,GDP,Number of Vehicles,Population,Land Area,Population Density,Total Chargers
42,Miami-Dade,192808376,4198.0,2700678,1900,1421.409474,2.0
5,Broward,132361553,3424.0,1978173,1203,1644.366584,2.0
27,Hillsborough,115772943,1914.0,1557655,1023,1522.634409,5.0
49,Palm Beach,106719346,1832.0,1547735,1964,788.052444,1.0
47,Orange,121343736,1649.0,1491071,903,1651.241417,9.0
...,...,...,...,...,...,...,...
12,DeSoto,1079903,0.0,36638,637,57.516484,0.0
22,Hamilton,588042,0.0,13748,514,26.747082,0.0
32,Lafayette,210912,0.0,8379,543,15.430939,0.0
48,Osceola,14415205,0.0,453025,1328,341.133283,0.0
62,Union,394035,0.0,15550,244,63.729508,0.0

In [ ]:
ML_TABLE = pd.concat([ML_TABLE, ML_TABLE2], ignore_index=True)

ML_TABLE = ML_TABLE.sort_values('Number of Vehicles', ascending=False)

# Drop duplicate rows based on all columns
ML_TABLE.drop_duplicates(inplace=True)
# Reset the index of the DataFrame after removing duplicates
ML_TABLE.reset_index(drop=True, inplace=True)

ML_TABLE

NameError: name 'pd' is not defined

In [ ]:
# Convert specified columns to integer type
columns_to_convert = ['Number of Vehicles', 'Total Chargers', 'GDP', 'Population', 'Land Area', 'Population Density']

# Use the astype method to convert to int
for column in columns_to_convert:
    ML_TABLE[column] = ML_TABLE[column].astype(int)

# Display the updated DataFrame to verify the changes
print(ML_TABLE[columns_to_convert].dtypes)
# Remove rows where "Number of Vehicles" is less than 1000
# ML_TABLE = ML_TABLE[ML_TABLE["Number of Vehicles"] >= 1000]
# Display the updated DataFrame (optional)
ML_TABLE

Number of Vehicles    int64
Total Chargers        int64
GDP                   int64
Population            int64
Land Area             int64
Population Density    int64
dtype: object

,County,Number of Vehicles,Total Chargers,GDP,Population,Land Area,Population Density
0,Los Angeles,581479,60698,801967353,9606925,4060,2366
1,Orange,263287,8522,273063592,3121138,793,3935
2,Santa Clara,223206,23365,390234709,1876849,1291,1453
3,San Diego,175122,10982,261671687,3262770,4210,775
4,Alameda,134796,6478,150532046,1616117,737,2192
...,...,...,...,...,...,...,...
158,Lincoln,0,0,489660,10928,2311,5
159,Skamania,0,0,270333,12041,1658,7
160,Ferry,0,0,190828,7198,2203,3
161,Garfield,0,0,173024,2294,711,3
162,Union,0,0,394035,15550,244,63

In [ ]:
# Save the DataFrame to a CSV file

ML_TABLE.to_csv('ML_TABLE.csv', index=False)


# Download the CSV file

from google.colab import files

files.download('ML_TABLE.csv')